version: "3"
services:
    db:
        container_name: mongodb
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
        command: mongod --quiet --logpath /dev/null
    server:
        build: ./server
        container_name: server
        ports:
            - 8888:8888
        volumes:
            - data-volume:/data/db
            -
            -
        links:
            - db
    web:
        build: ./web
        container_name: web
        ports:
            - 8889:8889
        volumes:
            - web:/app
            - 
volumes:
    mongodb:
    data-volume: