version: "3"
services:
    db:
        container_name: mongodb
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
    server:
        build: ./server
        container_name: server
        ports:
            - 8888:8888
        volumes:
            - ./server:/usr/src/app/server
            - /usr/src/app/server/node_modules
            - data-volume:/var/lib/shared
        links:
            - db
    web:
        build: ./front
        container_name: front
        ports:
            - 8889:8889
        volumes:
            - ./front:/usr/src/app/front
            - data-volume:/var/lib/shared
volumes:
    mongodb:
    data-volume: